### ISSUE TITLE
Rename group for the gradle plugin

### ISSUE THREAD

**Issue by liach** [MiserableNinja/Blossom#1]
The group of the plugin is still `ellune`, but now the group of this plugin is `miserableninja`. Would you change that?

**Comment by kashike** [comment]
I've migrated the plugin to the `ninja.miserable` namespace - blossom can still be found under the `net.ellune` namespace, but will not receive further updates.
https://plugins.gradle.org/plugin/ninja.miserable.blossom

**Comment by liach** [comment]
Great thanks kashike!
